### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by FalcoGer** [donbex/spkutils#1]
I get the following compilation error with g++ 9.3.0
```
CatFile.cpp:708:10: error: cannot convert ‘bool’ to ‘unsigned char*’ in return
  708 |   return false;
      |          ^~~~~
```
I got it to compile with a dirty replace with `return nullptr`, though I didn't check if the return of this function is ever checked for null (it should be)

**Comment by donbex** [comment]
I have pushed the fix, thanks. The function `CompressPCKData` is only called once in `PCKData`, which does test for null pointers.
